"""Audio analysis: spectral features, rhythm, harmony, loudness, segmentation."""

from wave_core.analysis.bands import (
    BAND_NAMES,
    BANDS_HZ,
    DEFAULT_SMOOTH_WINDOW,
    DEFAULT_TOP_DB,
    NUM_BANDS,
    BandEnergies,
    create_band_filterbank,
    extract_band_energy,
    extract_band_energy_from_audio,
    extract_band_energy_from_file,
)
from wave_core.analysis.harmony import (
    CAMELOT_MAP,
    KRUMHANSL_MAJOR,
    KRUMHANSL_MINOR,
    PITCH_NAMES,
    HarmonyFeatures,
    estimate_key_from_chroma,
    extract_harmony_features,
    extract_harmony_features_from_file,
    pitch_class_to_name,
)
from wave_core.analysis.rhythm import (
    DEFAULT_MAX_BPM,
    DEFAULT_MIN_BPM,
    RhythmFeatures,
    compute_bpm_confidence,
    correct_tempo_octave,
    detect_downbeats,
    extract_rhythm_features,
    extract_rhythm_features_from_file,
)
from wave_core.analysis.spectral import (
    HOP_LENGTH,
    N_FFT,
    N_MFCC,
    ROLLOFF_PERCENT,
    SAMPLE_RATE,
    WINDOW,
    SpectralFeatures,
    extract_spectral_features,
    extract_spectral_features_from_file,
    load_audio,
)

__all__ = [
    "BANDS_HZ",
    "BAND_NAMES",
    "CAMELOT_MAP",
    "DEFAULT_MAX_BPM",
    "DEFAULT_MIN_BPM",
    "DEFAULT_SMOOTH_WINDOW",
    "DEFAULT_TOP_DB",
    "HOP_LENGTH",
    "KRUMHANSL_MAJOR",
    "KRUMHANSL_MINOR",
    "NUM_BANDS",
    "N_FFT",
    "N_MFCC",
    "PITCH_NAMES",
    "ROLLOFF_PERCENT",
    "SAMPLE_RATE",
    "WINDOW",
    "BandEnergies",
    "HarmonyFeatures",
    "RhythmFeatures",
    "SpectralFeatures",
    "compute_bpm_confidence",
    "correct_tempo_octave",
    "create_band_filterbank",
    "detect_downbeats",
    "estimate_key_from_chroma",
    "extract_band_energy",
    "extract_band_energy_from_audio",
    "extract_band_energy_from_file",
    "extract_harmony_features",
    "extract_harmony_features_from_file",
    "extract_rhythm_features",
    "extract_rhythm_features_from_file",
    "extract_spectral_features",
    "extract_spectral_features_from_file",
    "load_audio",
    "pitch_class_to_name",
]
